# Generated by Django 5.0.7 on 2024-07-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointX', models.FloatField()),
                ('pointY', models.FloatField()),
            ],
        ),
    ]
